//export const FETCH_JSON_BEGIN   = 'FETCH_JSON_BEGIN';
//export const FETCH_JSON_SUCCESS = 'FETCH_JSON_SUCCESS';
//export const FETCH_JSON_FAILURE = 'FETCH_JSON_FAILURE';

export const FETCH_BANNERS_BEGIN   = 'FETCH_BANNERS_BEGIN';
export const FETCH_BANNERS_SUCCESS = 'FETCH_BANNERS_SUCCESS';
export const FETCH_BANNERS_FAILURE = 'FETCH_BANNERS_FAILURE';

export const SET_BANNER_PLAYING = 'SET_BANNER_PLAYING'
export const SET_BANNER_STOPPED = 'SET_BANNER_STOPPED'
export const SET_BANNER_ROLLED_OVER = 'SET_BANNER_ROLLED_OVER'



export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'

export const SCREEN_RESIZE = 'SCREEN_RESIZE';



/*






export const SHOW_ALL_BANNERS = 'SHOW_ALL_BANNERS'
export const HTML5_BANNERS = 'HTML5_BANNERS'
export const FLASH_BANNERS = 'FLASH_BANNERS'


export const SET_BANNER_PLAYING = 'SET_BANNER_PLAYING'
export const SET_BANNER_STOPPED_PLAYING = 'SET_BANNER_STOPPED_PLAYING'
export const SET_BANNER_ROLLED_OVER = 'SET_BANNER_ROLLED_OVER'

*/
